apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Certificats publics des autorités racine et intermédiaire (émettrice)
  name: {{ include "step-ca-secrets.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
data:
  intermediate_ca.crt: |-{{ required "certificats.intermediate_ca" .Values.certificats.intermediate_ca | nindent 4 }}
  root_ca.crt: |-{{ required "certificats.root_ca" .Values.certificats.root_ca | nindent 4 }}
